= Miscellaneous
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 10
:toc-title:

toc::[]


Write a management command
++++++++++++++++++++++++++

[source,bash]
....
# in any app, create the following structure

├── management
│   ├── __init__.py
│   └── commands
│       ├── __init__.py
│       └── mynewmanagementcommand.py
....

[source,python]
....
# mynewmanagementcommand.py

from django.core.management.base import BaseCommand, CommandError


class Command(BaseCommand):

    help_text = 'A new management command for fun'
    can_import_settings = True

    def __init__(self, *args, **kwargs):
        super(Command, self).__init__(*args, **kwargs)
        # do whatever processing is required here

    def add_arguments(self, parser):
        parser.add_argument('argument_1', nargs='?',
                            help='Specify Argument 1 here')
        parser.add_argument('argument_2', nargs='?',
                            help='Specify Argument 2 here')

    def handle(self, *args, **options):
        if not options['argument_1'] or not options['argument_2']:
            raise CommandError("Option `--argument_1... --argument_2...` must be specified.")

        # do some processing here now
....

Write a custom context processor
++++++++++++++++++++++++++++++++

[source,python]
....

def get_some_custom_value(request):
    return {
        'some_custom_key': 'some_custom_value'
    }

# Include the following in CONTEXT_PROCESSOR in settings
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ join(APP_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                ...
                'path.to.get_some_custom_value',
            ]
        },
    },
]
....

Cache operations
++++++++++++++++

[source,python]
....
from django.core import cache

# set mykey: myvalue
cache.set('mykey', 'myvalue')
# get value
cache.get('mykey')
# delete value
cache.delete('mykey')
....

Get request middleware
++++++++++++++++++++++

This is required to access request in places where it is not available
like model save. Use
https://pypi.org/project/django-contrib-requestprovider/[this] package.

Execute a management command from view
++++++++++++++++++++++++++++++++++++++

Many a times, some operational task is required to be executed through
management command and views. Views gives us the power to control
various parameters.

[source,python]
....
import os
import subprocess
from os.path import join

manage_py_location = join(os.getcwd(), 'manage.py')
python_path = join(os.getcwd(), '..', 'pyenv', 'bin', 'python')
log_file_dir = join(os.getcwd(), '..', 'logs')
log_file_path = join(log_file_dir, 'mynewmanagementcommand.log')
file = open(log_file_path, 'a+')
error_log_file_path = join(log_file_dir, 'mynewmanagementcommanderror.log')
error_file = open(error_log_file_path, 'a+')
subprocess.Popen([python_path, manage_py_location, 'mynewmanagementcommand', argument1, argument2],
                 env=os.environ.copy(), stdout=file, stderr=error_file)
....
