= Third Party Packages
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 10
:toc-title:

toc::[]

Pika(rabbitmq)
^^^^^^^^^^^^^^

Create a connection
+++++++++++++++++++

[source,python]
....
import pika

connection_string = 'amqp://{username}:{password}@{host}?heartbeat=60'.format(
    username=RABBIT_MQ_USERNAME, password=RABBIT_MQ_PASSWORD,
    host=RABBIT_MQ_HOST)
parameters = pika.connection.URLParameters(connection_string)
connection = pika.BlockingConnection(parameters)
channel = connection.channel()
....

Create a exchange and queue
+++++++++++++++++++++++++++

[source,python]
....
import pika

connection_string = 'amqp://{username}:{password}@{host}?heartbeat=60'.format(
    username=RABBIT_MQ_USERNAME, password=RABBIT_MQ_PASSWORD,
    host=RABBIT_MQ_HOST)
parameters = pika.connection.URLParameters(connection_string)
connection = pika.BlockingConnection(parameters)
channel = connection.channel()
# create exchange
channel.exchange_declare(exchange=EXCHANGE_NAME,type=EXCHANGE_TYPE)
# create queue
channel.queue_declare(queue=QUEUE_NAME, durable=True)
# bind to queue by using binding key
channel.queue_bind(exchange=EXCHANGE_NAME,
    queue=QUEUE_NAME,
    routing_key='bindingkey.*.*'
)
....

Publish message
+++++++++++++++

[source,python]
....
import json
import pika

connection_string = 'amqp://{username}:{password}@{host}?heartbeat=60'.format(
    username=RABBIT_MQ_USERNAME, password=RABBIT_MQ_PASSWORD,
    host=RABBIT_MQ_HOST)
parameters = pika.connection.URLParameters(connection_string)
connection = pika.BlockingConnection(parameters)
channel = connection.channel()
# create exchange
channel.exchange_declare(exchange=EXCHANGE_NAME,type=EXCHANGE_TYPE)
# create queue
channel.queue_declare(queue=QUEUE_NAME, durable=True)

# create message
message = {
    'key1': 'value1',
    'key2': 'value2',
}
channel.basic_publish(exchange=EXCHANGE_NAME,
    routing_key='routingkey.*.*',
    body=json.dumps(message),
    properties=pika.BasicProperties(delivery_mode=2)
)
....

Requests
^^^^^^^^

Get request with queryparams
++++++++++++++++++++++++++++

[source,python]
....
import json
import requests

query_params = {
    'q1': 'value1',
    'q2': 'value2',
}

headers = {
    'Content-Type': 'application/json',
}

try:
    response = requests.get(url, data=json.dumps(query_params), headers=headers, timeout=10)
except Exception as e:
    print 'Failed to create request', e
    response = None

if response and response.status_code == requests.codes.ok:
    print '200 status code received'
....

Post request with request body
++++++++++++++++++++++++++++++

[source,python]
....
import json
import requests

post_data = {
    'key1': 'value1',
    'key2': 'value2',
}

headers = {
    'Content-Type': 'application/json',
}

try:
    response = requests.post(url, data=json.dumps(post_data), headers=headers)
except Exception as e:
    print 'Failed to create request', e
    response = None
....

Generic way to do both get/post request
+++++++++++++++++++++++++++++++++++++++

[source,python]
....
import requests

post_data = {
    'key1': 'value1',
    'key2': 'value2',
}

headers = {
    'Content-Type': 'application/json',
}

method = 'POST'

req_args = {
    'data': post_data
}

try:
    response = requests.request(method, url, headers=headers, **req_args)
except Exception as e:
    print 'Failed to create request', e
    response = None
....

BeautifulSoup
^^^^^^^^^^^^^

Find particular tag
+++++++++++++++++++

[source,python]
....
from bs4 import BeautifulSoup

def find_particular_tags(s, tag):
    soup = BeautifulSoup(s, 'html.parser')
    return soup.select(tag)


def find_img_tags(s):
    soup = BeautifulSoup(s, 'html.parser')
    img = soup.select('img')
    return [i['src'] for i in img if i['src']]
....

Cassandra Client
^^^^^^^^^^^^^^^^

Select Query example
++++++++++++++++++++

[source,python]
....
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider

auth_provider = PlainTextAuthProvider(
    username=CASSANDRA_USERNAME, password=CASSANDRA_PASSWORD)

cluster = Cluster(auth_provider=auth_provider)
session = cluster.connect()
session.set_keyspace(CASSANDRA_KEYSPACE)

rows = session.execute('select * from {}.table_name'.format(CASSANDRA_KEYSPACE))
for row in rows:
    print row.id, row.name
....

Update Query example
++++++++++++++++++++

[source,python]
....
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider

auth_provider = PlainTextAuthProvider(
    username=CASSANDRA_USERNAME, password=CASSANDRA_PASSWORD)

CASSANDRA_KEYSPACE = 'mykeyspace'
cluster = Cluster(auth_provider=auth_provider)
session = cluster.connect()
session.set_keyspace(CASSANDRA_KEYSPACE)

session.execute('Update mykeyspace.table_name set name = 'newname' where id = %s ', (row_id,))
....

Mysql Client
^^^^^^^^^^^^

Insert Query example
++++++++++++++++++++

[source,python]
....
import MySQLdb

db = MySQLdb.connect(DB_HOST, DB_USER, DB_PASS, DB_NAME)
cursor = db.cursor()

query = 'INSERT into employee(name) VALUES (%s)'

cursor.execute(query, ['employee1', ])
db.commit()
db.close()

# with try-catch
try:
    cursor.execute(query, ['employee1', ])
    db.commit()
except Exception as e:
    db.rollback()
db.close()
....

Select Query example
++++++++++++++++++++

[source,python]
....
import MySQLdb

db = MySQLdb.connect(DB_HOST, DB_USER, DB_PASS, DB_NAME)
cursor = db.cursor()

query = 'Select id, age from employee where name = %s'

cursor.execute(query, ['employee1', ])
employee_1 = cursor.fetchone()
eid, eage = employee_1
db.close()
....

Insert On Duplicate Key Update example
++++++++++++++++++++++++++++++++++++++

[source,python]
....
import MySQLdb

db = MySQLdb.connect(DB_HOST, DB_USER, DB_PASS, DB_NAME)
cursor = db.cursor()

query = """
    INSERT INTO employee
        (employee_id, employee_name, salary, experience)
    VALUES
        (%(employee_id)s, %(employee_id)s, %(salary)s, %(experience)s)
    ON DUPLICATE KEY UPDATE
        salarty=VALUES(salary),
        experience=VALUES(experience);
"""

employee_data = [
    { "employee_id": 1, "employee_name": "ABC", "salary": 10, "experience": 1},
    { "employee_id": 2, "employee_name": "DEF", "salary": 11, "experience": 2},
]

cursor.execute(query, employee_data)
db.commit()
db.close()
....
